#!/usr/bin/env bun

/**
 * Reads all files from the template/ directory and generates src/template.generated.ts
 * with the templates object that can be imported at build time.
 */

import fs from 'fs/promises';
import path from 'path';

const TEMPLATE_DIR = path.join(import.meta.dir, '..', 'template');
const OUTPUT_FILE = path.join(import.meta.dir, '..', 'src', 'template.generated.ts');

// Files to skip
const SKIP_FILES = new Set(['.DS_Store']);

interface TemplateCategory {
  [relativePath: string]: string;
}

interface Templates {
  [category: string]: TemplateCategory;
}

async function readFilesRecursively(dir: string, baseDir: string): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  const entries = await fs.readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (SKIP_FILES.has(entry.name)) continue;

    const fullPath = path.join(dir, entry.name);
    const relativePath = path.relative(baseDir, fullPath);

    if (entry.isDirectory()) {
      const subFiles = await readFilesRecursively(fullPath, baseDir);
      Object.assign(files, subFiles);
    } else {
      const content = await fs.readFile(fullPath, 'utf-8');
      files[relativePath] = content;
    }
  }

  return files;
}

function escapeTemplateString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

async function main() {
  const templates: Templates = {};

  // Read each category directory
  const categories = await fs.readdir(TEMPLATE_DIR, { withFileTypes: true });

  for (const category of categories) {
    if (!category.isDirectory() || SKIP_FILES.has(category.name)) continue;

    const categoryPath = path.join(TEMPLATE_DIR, category.name);
    const files = await readFilesRecursively(categoryPath, categoryPath);
    templates[category.name] = files;
  }

  // Generate TypeScript output
  let output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/compile-templates.ts

export const templates = {\n`;

  for (const [category, files] of Object.entries(templates)) {
    output += `  ${category}: {\n`;
    for (const [filePath, content] of Object.entries(files)) {
      output += `    '${filePath}': \`${escapeTemplateString(content)}\`,\n\n`;
    }
    output += `  },\n\n`;
  }

  output += `} as const;\n\nexport type TemplateCategory = keyof typeof templates;\n`;

  await fs.writeFile(OUTPUT_FILE, output);
  console.log(`Generated ${OUTPUT_FILE}`);
}

main().catch((err) => {
  console.error('Failed to compile templates:', err);
  process.exit(1);
});
